const dataFields = {
	id                    : '[ID]',
	companyId             : '[CompanyID]',
	//x  : '[Invoice To Client ID]',
	//x  : '[Invoice To Agency ID]',
	//x  : '[Invoice By Client]',
	//x  : '[Invoice Client]',
	//x  : '[Agency Name]',
	//x  : '[ChargeSeqNo]',
	clientId              : '[Client ID]',
	//x  : '[Task ID]',
	//x  : '[Carer ID]',
	//x  : '[ShiftTypeNo]',
	//x  : '[ShiftTypeName]',
	//x  : '[Public Holiday]',
	//x  : '[Date Advised Carer]',
	//x  : '[Contact Method]',
	//x  : '[Advise Comments]',
	//x  : '[Chargeable Hrs]',
	//x  : '[Chargeable Shifts]',
	//x  : '[Chargeable KMs]',
	chargeRateQty         : '[Charge Rate Qty]',
	chargeRateCode        : '[Charge Rate Code]',
	chargeRateDescription : '[Charge Rate Description]',
	chargePerShift        : '[Charge Per Shift]',
	chargePerKm           : '[Charge Per KM]',
	//x  : '[Charge GST]',
	//x  : '[Pay Rate Per Hour]',
	//x  : '[Pay Rate Per Shift]',
	//x  : '[Pay Rate Per KM]',
	//x  : '[Payable Amount]',
	//x  : '[Paid Amount]',
	bookingTotalCharge    : '[Booking Total Charge]',
	bookingTotalGST       : '[Booking Total GST]',
	//x  : '[Location]',
	//x  : '[Description]',
	//x  : '[Carer Comments]',
	//x  : '[Carer KMs]',
	//x  : '[Carer Disbursements]',
	//x  : '[Charged Disbursements]',
	//x  : '[Additional Charge]',
	//x  : '[Additional Charge Description]',
	//x  : '[Date Time Confirmed]',
	//x  : '[Invoice Comments]',
	//x  : '[Carer Payment Comments]',
	//x  : '[Client Schedule Seq No]',
	//x  : '[Date Cancelled]',
	//x  : '[Cancel Charges]',
	//x  : '[SSMA_TimeStamp]',
	qtyCharged            : '[Qty Charged]',
	hoursCharged          : '[Hours Charged]',
	shiftsCharged         : '[Shifts Charged]',
	kmsCharged            : '[KMs Charged]',
	//x  : '[Percentage Charged]',
	//x  : '[Total Charge]',
	//x  : '[Total GST]',
	//x  : '[Date Invoiced]',
	//x  : '[Client Name]',
	//x  : '[Carer]',
	jobRef                : '[Job Ref]',
	taskName              : '[Task Name]',
	//x  : '[Carer Last Name]',
	//x  : '[Carer First Name]',
	activityId            : '[Activity ID]',
	//x  : '[Client First Name]',
	//x  : '[Client Last Name]',
	//x  : '[Employee Card ID]',
	//x  : '[Agencys Client]',
	//x  : '[Item Code]',
	//x  : '[Client Card ID]',
	//x  : '[Agency Card ID]',
	//x  : '[Employee Manager ID]',
	//x  : '[Service Start Date]',
	//x  : '[Service Finish Date]',
	//x  : '[PO Number]',
	//x  : '[Invoice No]',
	//x  : '[PricingGroupNo]',
	taskPrefix            : '[Task Prefix]',
	pricingGroupName      : '[PricingGroupName]',
	pricingGroupSuffix    : '[PricingGroupSuffix]',
	//x  : '[Invoice Terms Type]',
	//x  : '[Invoice Terms Days]',
	//x  : '[Date Time Transferred]',
	//x  : '[AcctIncomeCode]',
};

const dateTimeFields = {
	bookingDate : '[Booking Date]',
};

const timeFields = {
	startTime : '[Start Time]',
	endTime   : '[End Time]',
};

const dbModel = {
	tableName      : '[vwBookingsChargesDetails]',
	primaryKey     : dataFields.id,
	dataFields     : dataFields,
	dateTimeFields : dateTimeFields,
	timeFields     : timeFields,
};

module.exports.dbModel = dbModel;
