const dataFields = {
	companyId                            : '[CompanyID]',
	company                              : '[Company]',
	ABN                                  : '[ABN]',
	lastName                             : '[Last Name]',
	firstName                            : '[First Name]',
	email                                : '[E-mail Address]',
	jobTitle                             : '[Job Title]',
	businessPhone                        : '[Business Phone]',
	homePhone                            : '[Home Phone]',
	mobile                               : '[Mobile Phone]',
	fax                                  : '[Fax Number]',
	address                              : '[Address]',
	locality                             : '[City]',
	state                                : '[State/Province]',
	postcode                             : '[ZIP/Postal Code]',
	countryCode                          : '[CountryCode]',
	webPage                              : '[Web Page]',
	bankName                             : '[Bank Name]',
	bankBSB                              : '[Bank BSB]',
	bankAcct                             : '[Bank Acct]',
	companyLogo                          : '[Company Logo]',
	companyLogoWidth                     : '[Company Logo Width]',
	companyLogoHeight                    : '[Company Logo Height]',
	companySlogan                        : '[Company Slogan]',
	companyShortName                     : '[Company Short Name]',
	standardPayRateTypeNo                : '[StandardPayRateTypeNo]',
	afterHrsPayRateTypeNo                : '[AfterHrsPayRateTypeNo]',
	saturdayPayRateTypeNo                : '[SaturdayPayRateTypeNo]',
	sundayPayRateTypeNo                  : '[SundayPayRateTypeNo]',
	holidayPayRateTypeNo                 : '[HolidayPayRateTypeNo]',
	overnightPayRateTypeNo               : '[OvernightPayRateTypeNo]',
	overnightActivePayRateTypeNo         : '[OvernightActivePayRateTypeNo]',
	_24HrsPayRateTypeNo                  : '[24HrsPayRateTypeNo]',
	kmPayRateTypeNo                      : '[KmPayRateTypeNo]',
	kmChargeRate                         : '[KM Charge Rate]',
	kmActivityId                         : '[KM Activity ID]',
	kmItemCode                           : '[KM Item Code]',
	travelActivityId                     : '[Travel Activity ID]',
	showGettingStarted                   : '[ShowGettingStarted]',
	lastUpgradeNo                        : '[LastUpgradeNo]',
	versionNo                            : '[VersionNo]',
	clientDocsPath                       : '[Client Docs Path]',
	carersDocsPath                       : '[Carers Docs Path]',
	employeesDocsPath                    : '[Employees Docs Path]',
	agenciesDocsPath                     : '[Agencies Docs Path]',
	clientPhotosPath                     : '[Client Photos Path]',
	carersPhotosPath                     : '[Carers Photos Path]',
	employeesPhotosPath                  : '[Employees Photos Path]',
	myobPath                             : '[MYOB Path]',
	photoWidth                           : '[Photo Width]',
	photoHeight                          : '[Photo Height]',
	forwardDays                          : '[Forward Days]',
	maxTravelMinutes                     : '[Max Travel Minutes]',
	smsProvider                          : '[SMS Provider]',
	smsAccount                           : '[SMS Account]',
	smsPassword                          : '[SMS Password]',
	smsSendMsgIn                         : '[SMS Send Msg In]',
	smsFromEmail                         : '[SMS From Email]',
	smsSendInSubject                     : '[SMS Send In Subject]',
	emailSendAsSubject                   : '[Email Send As Subject]',
	gstRate                              : '[GSTRate]',
	gstTaxCode                           : '[GSTTaxCode]',
	noGstTaxCode                         : '[NoGSTTaxCode]',
	acctSystemNo                         : '[AcctSystemNo]',
	myobInterface                        : '[MYOB Interface]',
	myobInterfaceType                    : '[MYOB Interface Type]',
	sortClients                          : '[Sort Clients]',
	sortCarers                           : '[Sort Carers]',
	carerPortalIntroduction              : '[Carer Portal Introduction]',
	carerManagerPortalIntroduction       : '[Carer Manager Portal Introduction]',
	carerPortalUsed                      : '[Carer Portal Used]',
	carerPortalAllowEdit                 : '[Carer Portal Allow Edit]',
	carerPortalShowClientPhone           : '[Carer Portal Show Client Phone]',
	carerPortalURL                       : '[Carer Portal URL]',
	carerManagerPortalUsed               : '[Carer Manager Portal Used]',
	showTaskAbbreviation                 : '[Show Task Abbreviation]',
	pricingUsed                          : '[PricingUsed]',
	defaultPricingGroupPrivate           : '[DefaultPricingGroupPrivate]',
	defaultPricingGroupAgency            : '[DefaultPricingGroupAgency]',
	logSmsToContactHistory               : '[LogSMStoContactHistory]',
	useSMTP                              : '[UseSMTP]',
	serverSMTP                           : '[ServerSMTP]',
	portSMTP                             : '[PortSMTP]',
	authenticationTypeSMTP               : '[AuthenticationTypeSMTP]',
	defaultUserNameSMTP                  : '[DefaultUserNameSMTP]',
	defaultPasswordSMTP                  : '[DefaultPasswordSMTP]',
	useSslSMTP                           : '[UseSSLSMTP]',
	emailBccSMTP                         : '[SMTPEmailBCC]',
	carerRosterEmailSubject              : '[Carer Roster Email Subject]',
	carerRosterEmailBody                 : '[Carer Roster Email Body]',
	clientRosterEmailSubject             : '[Client Roster Email Subject]',
	clientRosterEmailBody                : '[Client Roster Email Body]',
	rosterNoOfDays                       : '[Roster No Of Days]',
	rosterStartWeekday                   : '[Roster Start Weekday]',
	invoiceTermsType                     : '[Invoice Terms Type]',
	invoiceTermsDays                     : '[Invoice Terms Days]',
	carePlanEmergency                    : '[Care Plan Emergency]',
	carePlanChangeofService              : '[Care Plan Change of Service]',
	carePlanChangeofDuties               : '[Care Plan Change of Duties]',
	carePlanOtherConditions              : '[Care Plan Other Conditions]',
	appendTaskPrefixToActivityId         : '[Append Task Prefix To Activity ID]',
	appendPricingGroupSuffixToActivityId : '[Append Pricing Group Suffix To Activity ID]',
	appendCancelSuffixToActivityId       : '[Append Cancel Suffix To Activity ID]',
	rosterShowTreatmentNotes             : '[Roster Show Treatment Notes]',
	separateClientInvoicesByAgency       : '[Separate Client Invoices By Agency]',
	exportShowTaskPrefix                 : '[Export Show Task Prefix]',
	exportShowTaskName                   : '[Export Show Task Name]',
	exportShowJobRef                     : '[Export Show Job Ref]',
	exportShowCardId                     : '[Export Show Card ID]',
	acctIncomeCode                       : '[AcctIncomeCode]',
	companyTimezone                      : '[Company Timezone]',
	defaultShiftTypeId                   : '[DefaultShiftTypeNo]',
};

const dateTimeFields = {
	lastScheduleDate : '[Last Schedule Date]',
	lastTravelDate   : '[Last Travel Date]',
};

const timeFields = {
	dayRateStartTime     : '[Day Rate Start Time]',
	eveningRateStartTime : '[Evening Rate Start Time]',
};
const dbModel = {
	tableName      : '[System Parameters]',
	primaryKey     : dataFields.companyId,
	dataFields     : dataFields,
	dateTimeFields : dateTimeFields,
	timeFields     : timeFields,
};

module.exports.dbModel = dbModel;
